project:
  type: website

website:
  title: "O❤️S"
  repo-url: "https://github.com/NLeSC/open-loves-science"
  page-footer: 
    left: "Made with ❤️ and Quarto"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: Cards
        menu: 
        - href: red-cards.qmd
          text: "Red Cards"
        - href: white-cards.qmd
          text: "White Cards"
      - href: rules.qmd
        text: "Rules"
    right: 
      - icon: github
        href: https://github.com/NLeSC/open-loves-science
        aria-label: GitHub

format:
  html:
    theme: [default, theme.scss]
    #css: styles.css
    toc: true



